// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/user-center/user-center-backend/app/user/service/internal/biz"
	"github.com/user-center/user-center-backend/app/user/service/internal/conf"
	"github.com/user-center/user-center-backend/app/user/service/internal/data"
	"github.com/user-center/user-center-backend/app/user/service/internal/server"
	"github.com/user-center/user-center-backend/app/user/service/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, userConstant *conf.UserConstant, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	cmdable := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(db, cmdable, logger, userConstant)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	recovery := data.NewRecovery(dataData)
	transaction := data.NewTransaction(dataData)
	userUseCase := biz.NewUserUseCase(userRepo, recovery, transaction, logger, userConstant)
	authRepo := data.NewAuthRepo(dataData, logger)
	authRepoUseCase := biz.NewAuthRepoUseCase(authRepo, recovery, transaction, logger)
	validateUseCase := biz.NewValidateUseCase()
	userService := service.NewUserService(userUseCase, authRepoUseCase, validateUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, userService, logger)
	httpServer := server.NewHTTPServer(confServer, userService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
